import type { AnimalSpecies } from '@supernatural/shared';

export const ANIMAL_SPECIES: Record<string, AnimalSpecies> = {
  bear: {
    id: 'bear',
    name: 'Bear',
    sprite: 'bear',
    size: 'large',
    tier: 'apex',
    diet: 'omnivore',
    habitat: ['forest', 'water_edge'],
    speed: 0.25,
    health: 200,
    attack: 35,
    detectionRange: 8,
    hunts: ['deer', 'pig', 'rabbit', 'horse', 'agent'],
    fleeThreshold: 0.15,
    maxPopulation: 5,
    foodDrop: 8,
    hungerDecay: 0.15,
    thirstDecay: 0.18,
    staminaDecay: 0.04,
    utilityWeights: { food: 0.8, water: 1.0, safety: 0.4, aggression: 1.2 },
    breedCooldown: 12000,
    litterSize: [1, 2],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'solitary',
    packSize: [1, 1],
    fearedBy: [],
    drops: { meat: 12, bone: 6, hide: 4, fat: 5, sinew: 3, teeth_claws: 4 },
    isScavenger: true,
  },
  tiger: {
    id: 'tiger',
    name: 'Tiger',
    sprite: 'tiger',
    size: 'large',
    tier: 'apex',
    diet: 'carnivore',
    habitat: ['forest'],
    speed: 0.55,
    health: 160,
    attack: 40,
    detectionRange: 12,
    hunts: ['deer', 'pig', 'goat', 'sheep', 'cow-0', 'horse', 'capybara', 'agent'],
    fleeThreshold: 0.20,
    maxPopulation: 4,
    foodDrop: 6,
    hungerDecay: 0.15,
    thirstDecay: 0.18,
    staminaDecay: 0.04,
    utilityWeights: { food: 1.0, water: 1.0, safety: 0.3, aggression: 1.6 },
    breedCooldown: 12000,
    litterSize: [1, 1],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'crepuscular',
    social: 'solitary',
    packSize: [1, 1],
    specialAbility: 'ambush',
    fearedBy: [],
    drops: { meat: 8, bone: 5, hide: 5, sinew: 3, teeth_claws: 5 },
    isScavenger: false,
  },
  alligator: {
    id: 'alligator',
    name: 'Alligator',
    sprite: 'alligator',
    size: 'large',
    tier: 'apex',
    diet: 'carnivore',
    habitat: ['water_edge'],
    speed: 0.15,
    health: 180,
    attack: 45,
    detectionRange: 6,
    hunts: ['duck', 'deer', 'pig', 'agent'],
    fleeThreshold: 0.0,
    maxPopulation: 6,
    foodDrop: 10,
    hungerDecay: 0.15,
    thirstDecay: 0.18,
    staminaDecay: 0.04,
    utilityWeights: { food: 0.9, water: 0.5, safety: 0.1, aggression: 1.4 },
    breedCooldown: 10000,
    litterSize: [2, 3],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'solitary',
    packSize: [1, 1],
    specialAbility: 'ambush',
    fearedBy: [],
    drops: { meat: 14, bone: 4, scales: 8, fat: 3, teeth_claws: 6 },
    isScavenger: false,
  },
  fox: {
    id: 'fox',
    name: 'Fox',
    sprite: 'fox',
    size: 'small',
    tier: 'mid_predator',
    diet: 'omnivore',
    habitat: ['forest', 'grassland'],
    speed: 0.50,
    health: 40,
    attack: 10,
    detectionRange: 10,
    hunts: ['rabbit', 'chicken', 'duck', 'rat', 'goat', 'squirrel', 'hedgehog'],
    fleeThreshold: 0.50,
    maxPopulation: 12,
    foodDrop: 2,
    hungerDecay: 0.10,
    thirstDecay: 0.12,
    staminaDecay: 0.04,
    utilityWeights: { food: 1.1, water: 1.0, safety: 1.2, aggression: 0.8 },
    breedCooldown: 4000,
    litterSize: [2, 3],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'crepuscular',
    social: 'solitary',
    packSize: [1, 2],
    specialAbility: 'steal_food',
    fearedBy: ['bear', 'tiger', 'dog-0', 'alligator'],
    drops: { meat: 3, bone: 2, hide: 2, sinew: 1, teeth_claws: 1 },
    isScavenger: true,
  },
  cat: {
    id: 'cat',
    name: 'Cat',
    sprite: 'cat',
    size: 'small',
    tier: 'mid_predator',
    diet: 'carnivore',
    habitat: ['forest', 'grassland'],
    speed: 0.45,
    health: 25,
    attack: 8,
    detectionRange: 8,
    hunts: ['rat', 'rabbit', 'squirrel'],
    fleeThreshold: 0.40,
    maxPopulation: 10,
    foodDrop: 1,
    hungerDecay: 0.10,
    thirstDecay: 0.12,
    staminaDecay: 0.04,
    utilityWeights: { food: 1.0, water: 1.0, safety: 1.0, aggression: 0.7 },
    breedCooldown: 5000,
    litterSize: [1, 3],
    tameable: true,
    tamingCost: 3,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'nocturnal',
    social: 'solitary',
    packSize: [1, 1],
    fearedBy: ['dog-0', 'fox', 'bear', 'tiger'],
    drops: { meat: 2, bone: 1, hide: 1, sinew: 1, teeth_claws: 1 },
    isScavenger: false,
  },
  'dog-0': {
    id: 'dog-0',
    name: 'Dog',
    sprite: 'dog-0',
    size: 'medium',
    tier: 'mid_predator',
    diet: 'carnivore',
    habitat: ['forest', 'grassland'],
    speed: 0.45,
    health: 60,
    attack: 15,
    detectionRange: 10,
    hunts: ['deer', 'rabbit', 'sheep', 'donkey', 'goat', 'capybara'],
    fleeThreshold: 0.30,
    maxPopulation: 15,
    foodDrop: 3,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.0, water: 1.0, safety: 0.8, aggression: 1.0 },
    breedCooldown: 6000,
    litterSize: [2, 4],
    tameable: true,
    tamingCost: 5,
    tamingProximity: 0,
    tamedBehavior: 'guard',
    activity: 'nocturnal',
    social: 'pack',
    packSize: [3, 6],
    specialAbility: 'howl',
    flockingWeights: { separation: 1.0, alignment: 1.2, cohesion: 1.0 },
    fearedBy: ['bear', 'tiger', 'alligator'],
    drops: { meat: 5, bone: 3, hide: 3, sinew: 2, teeth_claws: 2 },
    isScavenger: false,
  },
  rat: {
    id: 'rat',
    name: 'Rat',
    sprite: 'rat',
    size: 'tiny',
    tier: 'small_prey',
    diet: 'omnivore',
    habitat: ['forest', 'grassland', 'settlement'],
    speed: 0.35,
    health: 8,
    attack: 2,
    detectionRange: 6,
    hunts: [],
    fleeThreshold: 0.70,
    maxPopulation: 30,
    foodDrop: 1,
    hungerDecay: 0.08,
    thirstDecay: 0.10,
    staminaDecay: 0.03,
    utilityWeights: { food: 1.3, water: 1.0, safety: 1.5, aggression: 0.1 },
    breedCooldown: 1200,
    litterSize: [2, 4],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'nocturnal',
    social: 'swarm',
    packSize: [3, 10],
    specialAbility: 'steal_food',
    fearedBy: ['cat', 'fox', 'dog-0', 'bear'],
    drops: { meat: 1, fat: 1 },
    isScavenger: true,
  },
  deer: {
    id: 'deer',
    name: 'Deer',
    sprite: 'deer',
    size: 'medium',
    tier: 'large_herb',
    diet: 'herbivore',
    habitat: ['forest', 'grassland'],
    speed: 0.55,
    health: 60,
    attack: 12,
    detectionRange: 12,
    hunts: [],
    fleeThreshold: 0.80,
    maxPopulation: 20,
    foodDrop: 5,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.0, water: 1.0, safety: 1.6, aggression: 0.2 },
    breedCooldown: 6000,
    litterSize: [1, 2],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'crepuscular',
    social: 'herd',
    packSize: [4, 8],
    flockingWeights: { separation: 1.5, alignment: 1.5, cohesion: 0.8 },
    fearedBy: ['tiger', 'bear', 'dog-0', 'alligator', 'fox'],
    drops: { meat: 8, bone: 4, hide: 4, sinew: 3, teeth_claws: 2 },
    isScavenger: false,
  },
  'cow-0': {
    id: 'cow-0',
    name: 'Cow',
    sprite: 'cow-0',
    size: 'large',
    tier: 'large_herb',
    diet: 'herbivore',
    habitat: ['grassland'],
    speed: 0.18,
    health: 120,
    attack: 10,
    detectionRange: 8,
    hunts: [],
    fleeThreshold: 0.40,
    maxPopulation: 15,
    foodDrop: 8,
    hungerDecay: 0.15,
    thirstDecay: 0.18,
    staminaDecay: 0.04,
    utilityWeights: { food: 1.0, water: 1.0, safety: 1.0, aggression: 0.4 },
    breedCooldown: 6000,
    litterSize: [1, 1],
    tameable: true,
    tamingCost: 5,
    tamingProximity: 300,
    tamedBehavior: 'produce',
    activity: 'diurnal',
    social: 'herd',
    packSize: [5, 12],
    specialAbility: 'trample',
    flockingWeights: { separation: 0.8, alignment: 0.3, cohesion: 1.5 },
    fearedBy: ['tiger', 'bear', 'dog-0'],
    drops: { meat: 14, bone: 6, hide: 6, fat: 6, sinew: 4 },
    isScavenger: false,
  },
  horse: {
    id: 'horse',
    name: 'Horse',
    sprite: 'horse',
    size: 'large',
    tier: 'large_herb',
    diet: 'herbivore',
    habitat: ['grassland'],
    speed: 0.65,
    health: 100,
    attack: 18,
    detectionRange: 10,
    hunts: [],
    fleeThreshold: 0.60,
    maxPopulation: 10,
    foodDrop: 6,
    hungerDecay: 0.15,
    thirstDecay: 0.18,
    staminaDecay: 0.04,
    utilityWeights: { food: 1.0, water: 1.0, safety: 1.2, aggression: 0.3 },
    breedCooldown: 9000,
    litterSize: [1, 1],
    tameable: true,
    tamingCost: 8,
    tamingProximity: 500,
    tamedBehavior: 'follow',
    activity: 'diurnal',
    social: 'herd',
    packSize: [3, 8],
    flockingWeights: { separation: 1.0, alignment: 1.5, cohesion: 1.0 },
    fearedBy: ['tiger', 'bear', 'dog-0', 'alligator'],
    drops: { meat: 10, bone: 6, hide: 5, sinew: 4, fat: 3 },
    isScavenger: false,
  },
  pig: {
    id: 'pig',
    name: 'Pig',
    sprite: 'pig',
    size: 'medium',
    tier: 'medium_herb',
    diet: 'omnivore',
    habitat: ['forest'],
    speed: 0.35,
    health: 80,
    attack: 14,
    detectionRange: 8,
    hunts: [],
    fleeThreshold: 0.25,
    maxPopulation: 15,
    foodDrop: 6,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.1, water: 1.0, safety: 0.7, aggression: 0.9 },
    breedCooldown: 4000,
    litterSize: [2, 4],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'herd',
    packSize: [4, 8],
    fearedBy: ['tiger', 'bear', 'dog-0'],
    drops: { meat: 8, bone: 3, hide: 2, fat: 5, sinew: 2, teeth_claws: 2 },
    isScavenger: true,
  },
  goat: {
    id: 'goat',
    name: 'Goat',
    sprite: 'goat',
    size: 'medium',
    tier: 'medium_herb',
    diet: 'herbivore',
    habitat: ['grassland', 'rocky'],
    speed: 0.40,
    health: 50,
    attack: 10,
    detectionRange: 8,
    hunts: [],
    fleeThreshold: 0.50,
    maxPopulation: 12,
    foodDrop: 4,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.2, water: 1.0, safety: 0.9, aggression: 0.5 },
    breedCooldown: 4000,
    litterSize: [1, 2],
    tameable: true,
    tamingCost: 3,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'herd',
    packSize: [3, 6],
    fearedBy: ['tiger', 'bear', 'dog-0', 'fox'],
    drops: { meat: 5, bone: 3, hide: 3, sinew: 2, teeth_claws: 1 },
    isScavenger: false,
  },
  sheep: {
    id: 'sheep',
    name: 'Sheep',
    sprite: 'sheep',
    size: 'medium',
    tier: 'medium_herb',
    diet: 'herbivore',
    habitat: ['grassland'],
    speed: 0.25,
    health: 35,
    attack: 3,
    detectionRange: 10,
    hunts: [],
    fleeThreshold: 0.90,
    maxPopulation: 20,
    foodDrop: 3,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.0, water: 1.0, safety: 1.8, aggression: 0.1 },
    breedCooldown: 3000,
    litterSize: [1, 2],
    tameable: true,
    tamingCost: 2,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'flock',
    packSize: [6, 15],
    flockingWeights: { separation: 0.5, alignment: 0.8, cohesion: 2.0 },
    fearedBy: ['tiger', 'bear', 'dog-0', 'fox', 'alligator'],
    drops: { meat: 4, bone: 2, hide: 4, fat: 3, sinew: 1 },
    isScavenger: false,
  },
  donkey: {
    id: 'donkey',
    name: 'Donkey',
    sprite: 'donkey',
    size: 'medium',
    tier: 'medium_herb',
    diet: 'herbivore',
    habitat: ['grassland'],
    speed: 0.22,
    health: 90,
    attack: 12,
    detectionRange: 8,
    hunts: [],
    fleeThreshold: 0.30,
    maxPopulation: 8,
    foodDrop: 5,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.0, water: 1.0, safety: 0.6, aggression: 0.8 },
    breedCooldown: 6000,
    litterSize: [1, 1],
    tameable: true,
    tamingCost: 4,
    tamingProximity: 0,
    tamedBehavior: 'guard',
    activity: 'diurnal',
    social: 'herd',
    packSize: [2, 4],
    fearedBy: ['tiger', 'bear', 'dog-0', 'alligator'],
    drops: { meat: 7, bone: 4, hide: 4, sinew: 3 },
    isScavenger: false,
  },
  rabbit: {
    id: 'rabbit',
    name: 'Rabbit',
    sprite: 'rabbit',
    size: 'tiny',
    tier: 'small_prey',
    diet: 'herbivore',
    habitat: ['grassland', 'forest'],
    speed: 0.50,
    health: 12,
    attack: 0,
    detectionRange: 8,
    hunts: [],
    fleeThreshold: 1.0,
    maxPopulation: 30,
    foodDrop: 1,
    hungerDecay: 0.08,
    thirstDecay: 0.10,
    staminaDecay: 0.03,
    utilityWeights: { food: 1.3, water: 1.0, safety: 2.0, aggression: 0.0 },
    breedCooldown: 900,
    litterSize: [2, 3],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'crepuscular',
    social: 'herd',
    packSize: [3, 8],
    fearedBy: ['fox', 'cat', 'dog-0', 'bear', 'tiger', 'alligator'],
    drops: { meat: 2, bone: 1, hide: 1 },
    isScavenger: false,
  },
  chicken: {
    id: 'chicken',
    name: 'Chicken',
    sprite: 'chicken',
    size: 'tiny',
    tier: 'small_prey',
    diet: 'omnivore',
    habitat: ['grassland'],
    speed: 0.20,
    health: 15,
    attack: 1,
    detectionRange: 6,
    hunts: [],
    fleeThreshold: 0.80,
    maxPopulation: 20,
    foodDrop: 2,
    hungerDecay: 0.08,
    thirstDecay: 0.10,
    staminaDecay: 0.03,
    utilityWeights: { food: 1.1, water: 1.0, safety: 1.5, aggression: 0.0 },
    breedCooldown: 1500,
    litterSize: [1, 2],
    tameable: true,
    tamingCost: 1,
    tamingProximity: 0,
    tamedBehavior: 'produce',
    activity: 'diurnal',
    social: 'flock',
    packSize: [3, 8],
    specialAbility: 'egg_laying',
    eggRate: 1800,
    fearedBy: ['fox', 'cat', 'dog-0', 'rat'],
    drops: { meat: 2, bone: 1, feathers: 3, fat: 1 },
    isScavenger: false,
  },
  duck: {
    id: 'duck',
    name: 'Duck',
    sprite: 'duck',
    size: 'tiny',
    tier: 'small_prey',
    diet: 'omnivore',
    habitat: ['water_edge'],
    speed: 0.22,
    health: 15,
    attack: 1,
    detectionRange: 6,
    hunts: [],
    fleeThreshold: 0.80,
    maxPopulation: 15,
    foodDrop: 2,
    hungerDecay: 0.08,
    thirstDecay: 0.10,
    staminaDecay: 0.03,
    utilityWeights: { food: 1.0, water: 0.8, safety: 1.5, aggression: 0.0 },
    breedCooldown: 1800,
    litterSize: [1, 3],
    tameable: true,
    tamingCost: 2,
    tamingProximity: 0,
    tamedBehavior: 'produce',
    activity: 'diurnal',
    social: 'flock',
    packSize: [4, 10],
    specialAbility: 'egg_laying',
    eggRate: 2000,
    fearedBy: ['fox', 'alligator', 'cat'],
    drops: { meat: 2, bone: 1, feathers: 4, fat: 2 },
    isScavenger: false,
  },
  squirrel: {
    id: 'squirrel',
    name: 'Squirrel',
    sprite: 'squirrel',
    size: 'tiny',
    tier: 'small_prey',
    diet: 'herbivore',
    habitat: ['forest'],
    speed: 0.45,
    health: 10,
    attack: 0,
    detectionRange: 8,
    hunts: [],
    fleeThreshold: 1.0,
    maxPopulation: 15,
    foodDrop: 1,
    hungerDecay: 0.08,
    thirstDecay: 0.10,
    staminaDecay: 0.03,
    utilityWeights: { food: 1.2, water: 1.0, safety: 2.0, aggression: 0.0 },
    breedCooldown: 3000,
    litterSize: [1, 2],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'solitary',
    packSize: [1, 2],
    specialAbility: 'seed_disperse',
    fearedBy: ['cat', 'fox', 'dog-0'],
    drops: { meat: 1, hide: 1, feathers: 1 },
    isScavenger: false,
  },
  hedgehog: {
    id: 'hedgehog',
    name: 'Hedgehog',
    sprite: 'hedgehog',
    size: 'tiny',
    tier: 'small_prey',
    diet: 'omnivore',
    habitat: ['forest'],
    speed: 0.15,
    health: 20,
    attack: 0,
    detectionRange: 4,
    hunts: [],
    fleeThreshold: 0.0,
    maxPopulation: 8,
    foodDrop: 1,
    hungerDecay: 0.08,
    thirstDecay: 0.10,
    staminaDecay: 0.03,
    utilityWeights: { food: 1.0, water: 1.0, safety: 0.5, aggression: 0.0 },
    breedCooldown: 5000,
    litterSize: [1, 2],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'nocturnal',
    social: 'solitary',
    packSize: [1, 1],
    specialAbility: 'curl',
    fearedBy: ['fox', 'cat', 'dog-0', 'bear'],
    drops: { meat: 1, bone: 1, teeth_claws: 1, scales: 1 },
    isScavenger: false,
  },
  capybara: {
    id: 'capybara',
    name: 'Capybara',
    sprite: 'capybara',
    size: 'medium',
    tier: 'medium_herb',
    diet: 'herbivore',
    habitat: ['water_edge', 'grassland'],
    speed: 0.25,
    health: 45,
    attack: 3,
    detectionRange: 6,
    hunts: [],
    fleeThreshold: 0.70,
    maxPopulation: 12,
    foodDrop: 3,
    hungerDecay: 0.12,
    thirstDecay: 0.15,
    staminaDecay: 0.05,
    utilityWeights: { food: 1.0, water: 0.8, safety: 1.0, aggression: 0.0 },
    breedCooldown: 4000,
    litterSize: [1, 2],
    tameable: false,
    tamingCost: 0,
    tamingProximity: 0,
    tamedBehavior: 'passive',
    activity: 'diurnal',
    social: 'herd',
    packSize: [4, 8],
    specialAbility: 'peace_aura',
    flockingWeights: { separation: 0.8, alignment: 0.5, cohesion: 1.5 },
    fearedBy: ['tiger', 'bear', 'fox', 'alligator', 'dog-0'],
    drops: { meat: 5, bone: 2, hide: 3, fat: 3 },
    isScavenger: false,
  },
};

export function getSpecies(id: string): AnimalSpecies {
  const species = ANIMAL_SPECIES[id];
  if (!species) {
    throw new Error(`Unknown animal species: ${id}`);
  }
  return species;
}
